### ISSUE TITLE
For ESP32 it is not working

### ISSUE THREAD

**Issue by Engineerrandd** [dleval/STLED316S#2]
![Screenshot (2)](https://user-images.githubusercontent.com/86049142/122367955-8b012580-cf7a-11eb-95ac-4b4fb09e135e.png)

**Comment by dleval** [comment]
![image](https://user-images.githubusercontent.com/61865368/122398575-4d040180-cf7a-11eb-88db-9b0b7b3d0187.png)

The compilation problem is fixed with version v1.0.2.
I hope there are no other problems because I haven't tested this library on an ESP32.
