### ISSUE TITLE
How to use both string and int at same time

### ISSUE THREAD

**Issue by Engineerrandd** [dleval/STLED316S#4]
In dispUdec can't able to display the character. So I tried to use dispRAW to display character, but in dispRAW can't able to display 3 digit integer value.  For example, I am using 4 digit display, in that the 1st display should show "H" and the remaining display should show integer (loop (0-100)) at a time.
How it is possible by using your library.
Thank you in advance, eagerly waiting for your response.

**Comment by dleval** [comment]
Here is an example of how to perform the requested function :
```c
void loop() 
{
  //Display unsigned decimal number with H:
  for(uint8_t i=0;i<=100;i++) {
    dispUdecWithH(i);
    delay(200);
  }
}

void dispUdecWithH(uint32_t nbr)
{
  DIGITnum_t digitNbr = DIGITn4;
  stled.clearDisplay();
  if(nbr<100) digitNbr = DIGITn3;
  if(nbr<10) digitNbr = DIGITn2;
  stled.dispRAW(digitNbr,0x76);
  stled.dispUdec(nbr);
}
```
The letter 'H' is realised with the raw function. The position of the letter is adapted according to the size of the number to be displayed

![image](https://user-images.githubusercontent.com/61865368/133103340-024e59db-7ce6-47d5-bcd5-039f16d3fa47.png)
