### ISSUE TITLE
Keypad/STLED316s/Arduino

### ISSUE THREAD

**Issue by Engineerrandd** [dleval/STLED316S#6]
Is it possible to interface the keypad with STLED316? 
If yes, please provide an example code with a detailed explanation.
Thank you...

**Comment by dleval** [comment]
Hello,
It is possible to interface a keypad (8x2 matrix max) with the STLED316S driver.
You can find an example of an electronic diagram in the extras directory.
There are two examples of using a keypad with polling and with interrupt.

Example of a diagram from the STLED316S driver documentation:
![image](https://user-images.githubusercontent.com/61865368/133097084-60c91841-9f95-4ecc-bebb-beb56d202279.png)
Each column of the keypad is connected to the driver via a single diode.
The keypad lines must have a pull-down resistor.

**Comment by Engineerrandd** [comment]
Thank you for your response, can you send sample code for keypad
interfacing using stled316

**Comment by dleval** [comment]
**Example using polling method :**

```c
void loop() {
  uint8_t data = stled.readData(stled.STLED316S_ADDR_KEY_DATA1);
  if(data != 0) {
    //A key is pressed. Do something
  }
}
```

**Example using interrupt method :**
_The INT output of the STLED316S must be connected to an interrupt input of the MCU._
```c
//Number of LED digit connected on driver:
#define NBR_OF_DIGIT  6
//Pinout :
#define STB_PIN       8
#define CLK_PIN       13
#define DATA_PIN      11
#define INT_PIN       2

//STLED316S driver object
STLED316S stled(NBR_OF_DIGIT, STB_PIN, CLK_PIN, DATA_PIN);

bool doReadKeys = false;

void dispInterrupt(void)
{
  //Interruption by pressing a key
  doReadKeys = true;
}

void setup() {
  stled.begin();

  //Interrupt configuration
  pinMode(INT_PIN, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(INT_PIN), dispInterrupt, FALLING);
}

void loop() 
{
  if(doReadKeys)
  {
    uint8_t data = stled.readData(stled.STLED316S_ADDR_KEY_DATA1);
    //A key is pressed. Do something
  }
}
```

**Comment by dleval** [comment]
I wrote a new function for reading the KeyScan in version v1.1.0 of the library.
Here is an example of use:
```c
void loop() {
  uint16_t keyData = stled.readKeyScan();
  if(keyData != 0) {
    //A key is pressed. Do something
  }
}
```
