### ISSUE TITLE
Can't display characters

### ISSUE THREAD

**Issue by Alex-Scheff** [dleval/STLED316S#8]
Hi, this might not be a real issue but this is the only way I found to contact you, David.

So I want to display some characters on my display, how do I do that?
I tried using the dispRAW Function to display an O (Yes I could use 0 but that doesn't work for C, A, U ...), but if I use it like this:
```
    stled2.dispRAW(DIGITn1, SEG1);
    stled2.dispRAW(DIGITn1, SEG2);
    stled2.dispRAW(DIGITn1, SEG3);
    stled2.dispRAW(DIGITn1, SEG4);
    stled2.dispRAW(DIGITn1, SEG5);
    stled2.dispRAW(DIGITn1, SEG6);
```
It only flickers. 
Probably because when displaying new raw data the previous one gets deleted and not shown side by side how I have hoped.
The possibility to add more segments to the dispRAW function like this:
```
    stled2.dispRAW(DIGITn1, SEG1, SEG2, SEG3, SEG4, SEG5, SEG6);
```
or similarly might be a solution. If that is possible I have no idea, I'm not that good at programming yet.
If at the moment there is no way to show characters (or own segment compilations) you might be able to add this function?
I love this library, it's the only one that makes my project possible, so thank you so much in advance.

**Comment by dleval** [comment]
Hello,
Indeed, in the dispRAW function, the second argument corresponds to the raw value of the state of all the segments.
However, each SEGx constant represents a single bit. It's possible to add them together to create a character :
```c
stled2.dispRAW(DIGITn1, (SEG1 + SEG2 + SEG3 + SEG4 + SEG5 + SEG6));
```
or
```c
stled2.dispRAW(DIGITn1, (SEG1 | SEG2 | SEG3 | SEG4 | SEG5 | SEG6));
```
I haven't tested this solution but normally it should work.
Please try and give feedback. If it doesn't work I will add a function.

**Comment by Alex-Scheff** [comment]
Hi David, thank you for your fast response.
Yes, that works!
Thank you so much.
